Microsoft Excel is arguably the most widely used programming environment worldwide @gordon_lambda_2021. The interface can be seen as the IDE, and the worksheet and the formulae as the code. At some pension fund companies, it is reportedly#footnote[Based on several interviews with employees at Info Support B.V.] used to maintain and calculate the pension fund interest for all of its customers. 

Pension fund employees use Excel worksheets as their tool to compute the forecasts under a range of different situations. There are more than a thousand situations per person. For example, a user might want to know what their pension will look like if they take their pension when 65 years old, given the economy has been good. As such, Excel is used as an API that calculates these situations. 

For some companies, all of these situations need to be calculated for nearly 1 million customers every year. Due to the slow nature of Excel, this process usually takes weeks, encountering many crashes that slow down progress even further. To combat this, one of the partners of the pension funds, Info Support B.V., manually converted such an Excel file to a high-level programming language in order to increase performance and stability. 

However, the laws surrounding pensions change every year @ministerie_van_binnenlandse_zaken_en_koninkrijksrelaties_wetstechnische_2025. As a result, ways to calculate the aforementioned situations need to be changed. Since pension fund employees are unable to maintain the code provided by Info Support, after every change, this needs to be manually changed by Info Support. This resource-intensive operation could be automated. Hence, Info Support---as part of the ongoing _GROENpensioen_ project#footnote[The graduation project is called 'Van GRIJSPensioen naar GROENpensioen' and can be found at #link("https://carriere.infosupport.com/groenpensioen/")]---aims to automatically convert these calculations from Microsoft Excel to high performing code to improve reliability, performance and ultimately durability of the pension fund calculation process. 



// One of the partners of the pension funds, Info Support B.V., converted the tool to a high-level programming language, but this was done manually. Since the pension fund employees are not able to program and extend the code, when another scenario should be added, only the excel file is updated and needs to be manually converted by info support. Hence, Info Support---as part of the ongoing _GROENpensioen_ project---aims to automatically convert these calculations from Microsoft Excel to high performing code to improve reliability, performance and durability. While there have been work on extracting models from spreadsheets, there is no tool to convert the calculations in a spreadsheet to higher-level code.

// The converting process entails multiple steps, from compiling excel formulas to a generic programming language to applying optimalizations to the dataflow. In this thesis, we will explore the former problem of compiling excel files to coherent, high-performing higher level programming language code in the context of actuarial computations. This approach will therefore focus on the computational model of the excel engine.